name:                status-notifier-item
version:             0.3.1.0
github:              "IvanMalison/status-notifier-item"
license:             BSD3
author:              "Ivan Malison"
maintainer:          "IvanMalison@gmail.com"
copyright:           "2018 Ivan Malison"

category: Desktop
synopsis: A wrapper over the StatusNotifierItem/libappindicator dbus specification

extra-source-files:
- README.md
- ChangeLog.md
- xml/*

description: Please see the README on Github at <https://github.com/IvanMalison/status-notifier-item#readme>

library:
  source-dirs: src
  dependencies:
    - base >= 4.7 && < 5
    - byte-order
    - bytestring
    - bytestring-to-vector
    - containers
    - dbus >= 1.2.1 && < 2.0.0
    - filepath
    - hslogger
    - lens
    - template-haskell
    - text
    - transformers
    - vector

executables:
  status-notifier-watcher:
    source-dirs: ./watcher
    dependencies:
      - base >= 4.7 && < 5
      - dbus >= 1.0.0 && < 2.0.0
      - dbus-hslogger >= 0.1.0.1 && < 0.2.0.0
      - hslogger
      - status-notifier-item
      - optparse-applicative
    main: Main.hs
  sni-cl-tool:
    source-dirs: ./tool
    dependencies:
      - base >= 4.7 && < 5
      - dbus > 1.0
      - status-notifier-item
      - optparse-applicative
    main: Main.hs
  status-notifier-item-static:
    source-dirs: ./item
    dependencies:
      - base >= 4.7 && < 5
      - status-notifier-item
      - optparse-applicative
    main: Main.hs
